export default {
  login: "Deepikasanu",
  id: 60472398,
  node_id: "MDQ6VXNlcjYwNDcyMzk4",
  avatar_url: "https://avatars.githubusercontent.com/u/60472398?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Deepikasanu",
  html_url: "https://github.com/Deepikasanu",
  followers_url: "https://api.github.com/users/Deepikasanu/followers",
  following_url:
    "https://api.github.com/users/Deepikasanu/following{/other_user}",
  gists_url: "https://api.github.com/users/Deepikasanu/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Deepikasanu/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Deepikasanu/subscriptions",
  organizations_url: "https://api.github.com/users/Deepikasanu/orgs",
  repos_url: "https://api.github.com/users/Deepikasanu/repos",
  events_url: "https://api.github.com/users/Deepikasanu/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Deepikasanu/received_events",
  type: "User",
  site_admin: false,
  name: "Deepika C",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 2,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-01-30T13:00:29Z",
  updated_at: "2021-05-11T17:03:20Z",
};